### ISSUE TITLE
19/05/2023 - LeaderBoard Issue

### ISSUE THREAD

**Issue by unorjikingsley** [katfogy/leadership-board-game#11]
Awesome code. your code is linter free and follows all good practice principles. well done champ.
A little issue is the use of innerHTML, this gives your code open to hackers.

**Comment by forLoop94** [comment]
I love how your page refreshes on its own when the submit button is clicked. Nice job Foga.

**Comment by yashodhicy** [comment]
I have seen you have done an excellent work on this. UI is so good and the functionality is impressive.
It is better 

1. if you can add some range to scores 

2. Also rather than refreshing the page when you click on the refresh button you can refresh only dom elements.

**Comment by katfogy** [comment]
Thank you guys for the reviews
